# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew.
#
# The context of this file is documented in https://docs.brew.sh/Formula-Cookbook
#
class Aish < Formula
  desc "AI shell helper"
  homepage "https://github.com/TonnyWong1052/aish"
  url "https://github.com/TonnyWong1052/aish/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "4f3f95ed00339ea1a4dceb9848b84c050db5794111c898da3dbfca1a893eb9a3"
  license "MIT"

  depends_on "go" => :build

  def install
    # The build command is derived from scripts/install.sh
    system "go", "build", "-o", "aish", "./cmd/aish"
    bin.install "aish"
  end

  def caveats
    <<~EOS
      Installation complete! To finish setup, run the following command:
        aish init
    EOS
  end

  test do
    # This test is basic and just checks if the binary can be executed.
    # You might want to add a more comprehensive test here.
    assert_match "aish version", shell_output("#{bin}/aish --version")
  end
end