# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew.
#
# The context of this file is documented in https://docs.brew.sh/Formula-Cookbook
#
class Aish < Formula
  desc "AI shell helper"
  homepage "https://github.com/TonnyWong1052/aish"
  url "https://github.com/TonnyWong1052/aish/archive/refs/tags/v0.0.2.tar.gz"
  # 對齊 v0.0.2 GitHub tag 壓縮包的實際校驗值
  sha256 "5077202726d84dfd1a3b6e4f22c2c98fa8e81aae9c02dd9611592ceb2c1cd67a"
  version "0.0.2"
  license "MIT"

  depends_on "go" => :build

  def install
    # 透過 ldflags 注入版本字串，確保 `aish --version` 與公式 version 一致
    ldflags = "-s -w -X main._version=v#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"aish"), "./cmd/aish"
  end

  def caveats
    <<~EOS
      Installation complete! To finish setup, run the following command:
        aish init
    EOS
  end

  test do
    # This test is basic and just checks if the binary can be executed.
    # You might want to add a more comprehensive test here.
    assert_match "aish v0.0.2", shell_output("#{bin}/aish version")
  end
end
